version: '3.9'
services:
  tuwaiq_prj_server:
    image: tuwaiq_prj_server:latest
    build: .
    ports:
      - '3001:3001'
  tuwaiq_prj_client:
    image: tuwaiq_prj_client:latest
    environment:
      PORT: 3000
      PROXY_API: http://devops_backend:3001/
    ports:
      - '3000:3000'
